version: 2

workflows:
  version: 2
  test_and_release:
    jobs:
      - test_and_make

      - deploy:
          requires:
            - test_and_make
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            # branches:
            #   ignore: /.*/

jobs:
  test_and_make:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: node-deps-v1-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: node-deps-v1-{{ checksum "package-lock.json" }}
          paths:
            - $HOME/.npm
      - run: npm run lint
      - run: npm run compile
      - run: npm run test
      - run: npm run coverage
      - run: npm run report-coverage
      - store_artifacts:
          path: ./coverage
      - persist_to_workspace:
          root: .
          paths:
            - dist

  deploy:
      docker:
      - image: circleci/node:10
      steps:
        - attach_workspace:
            at: .
        - run:
            name: Authenticate with registry
            command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/.npmrc
        - run:
            name: Publish package
            command: npm publish --access public
